version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: paga_facil
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: paga_facil
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sueldo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d paga_facil"]
      interval: 3s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paga_facil_app
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgrespassword
      DATABASE_NAME: paga_facil
      DATABASE_SYNC: "true"
      PORT: 3001
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sueldo_network

volumes:
  pgdata:
    driver: local

networks:
  sueldo_network:
    driver: bridge
